// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: whitelist.proto

package IPWhitelist

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WhitelistData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to DataType:
	//	*WhitelistData_Iso
	//	*WhitelistData_Locale
	DataType isWhitelistData_DataType `protobuf_oneof:"data_type"`
	Ip       string                   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Country  []string                 `protobuf:"bytes,4,rep,name=country,proto3" json:"country,omitempty"`
}

func (x *WhitelistData) Reset() {
	*x = WhitelistData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whitelist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistData) ProtoMessage() {}

func (x *WhitelistData) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistData.ProtoReflect.Descriptor instead.
func (*WhitelistData) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{0}
}

func (m *WhitelistData) GetDataType() isWhitelistData_DataType {
	if m != nil {
		return m.DataType
	}
	return nil
}

func (x *WhitelistData) GetIso() bool {
	if x, ok := x.GetDataType().(*WhitelistData_Iso); ok {
		return x.Iso
	}
	return false
}

func (x *WhitelistData) GetLocale() string {
	if x, ok := x.GetDataType().(*WhitelistData_Locale); ok {
		return x.Locale
	}
	return ""
}

func (x *WhitelistData) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *WhitelistData) GetCountry() []string {
	if x != nil {
		return x.Country
	}
	return nil
}

type isWhitelistData_DataType interface {
	isWhitelistData_DataType()
}

type WhitelistData_Iso struct {
	Iso bool `protobuf:"varint,1,opt,name=iso,proto3,oneof"`
}

type WhitelistData_Locale struct {
	Locale string `protobuf:"bytes,2,opt,name=locale,proto3,oneof"`
}

func (*WhitelistData_Iso) isWhitelistData_DataType() {}

func (*WhitelistData_Locale) isWhitelistData_DataType() {}

type WhitelistReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpIsWhitelisted string `protobuf:"bytes,1,opt,name=ip_is_whitelisted,json=ipIsWhitelisted,proto3" json:"ip_is_whitelisted,omitempty"`
	Error           string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *WhitelistReturn) Reset() {
	*x = WhitelistReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whitelist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistReturn) ProtoMessage() {}

func (x *WhitelistReturn) ProtoReflect() protoreflect.Message {
	mi := &file_whitelist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistReturn.ProtoReflect.Descriptor instead.
func (*WhitelistReturn) Descriptor() ([]byte, []int) {
	return file_whitelist_proto_rawDescGZIP(), []int{1}
}

func (x *WhitelistReturn) GetIpIsWhitelisted() string {
	if x != nil {
		return x.IpIsWhitelisted
	}
	return ""
}

func (x *WhitelistReturn) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_whitelist_proto protoreflect.FileDescriptor

var file_whitelist_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x22,
	0x74, 0x0a, 0x0d, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x03, 0x69, 0x73, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x03, 0x69, 0x73, 0x6f, 0x12, 0x18, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x0b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x53, 0x0a, 0x0f, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x70, 0x5f, 0x69,
	0x73, 0x5f, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x70, 0x49, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b,
	0x49, 0x50, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_whitelist_proto_rawDescOnce sync.Once
	file_whitelist_proto_rawDescData = file_whitelist_proto_rawDesc
)

func file_whitelist_proto_rawDescGZIP() []byte {
	file_whitelist_proto_rawDescOnce.Do(func() {
		file_whitelist_proto_rawDescData = protoimpl.X.CompressGZIP(file_whitelist_proto_rawDescData)
	})
	return file_whitelist_proto_rawDescData
}

var file_whitelist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_whitelist_proto_goTypes = []interface{}{
	(*WhitelistData)(nil),   // 0: whitelist.v1.WhitelistData
	(*WhitelistReturn)(nil), // 1: whitelist.v1.WhitelistReturn
}
var file_whitelist_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_whitelist_proto_init() }
func file_whitelist_proto_init() {
	if File_whitelist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_whitelist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whitelist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_whitelist_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*WhitelistData_Iso)(nil),
		(*WhitelistData_Locale)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_whitelist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whitelist_proto_goTypes,
		DependencyIndexes: file_whitelist_proto_depIdxs,
		MessageInfos:      file_whitelist_proto_msgTypes,
	}.Build()
	File_whitelist_proto = out.File
	file_whitelist_proto_rawDesc = nil
	file_whitelist_proto_goTypes = nil
	file_whitelist_proto_depIdxs = nil
}
